name: PowerShell CI

on:
  push:
    branches:
      - main
    paths:
      - 'Init/win/**'
  pull_request:
    branches:
      - main
    paths:
      - 'Init/win/**'

jobs:
  pester-tests:
    name: 'Run Pester Tests'
    runs-on: windows-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run Pester tests for init script
        shell: pwsh
        run: |
          Install-Module -Name Pester -Force -SkipPublisherCheck
          Invoke-Pester -Script 'Init/win/init.Tests.ps1' -CI